apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wf-clusterrole
  namespace: wavefront
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wf-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
- kind: ServiceAccount # Omit apiGroup
  name: default
  namespace: wavefront